# Generated by Django 3.2.16 on 2023-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_subscription_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
