# Generated by Django 3.2.16 on 2023-02-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_subscription_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
