# Generated by Django 3.2.16 on 2023-02-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_default_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_subscription_status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
