# Generated by Django 3.2.16 on 2023-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20230221_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_street_address2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
