# Generated by Django 3.2.16 on 2023-02-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20230221_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
