# Generated by Django 3.2.16 on 2023-02-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_options', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipoptions',
            options={'verbose_name_plural': 'Membership Options'},
        ),
    ]
