# Generated by Django 3.2.16 on 2023-02-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20230212_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
