# Generated by Django 3.2.16 on 2023-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230206_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=254),
        ),
    ]
