# Generated by Django 3.2.16 on 2023-02-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230223_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='home.Playlist'),
        ),
    ]
